name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
          - windows
          - darwin
        goarch:
          - amd64
          - arm64
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.24"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set Asset Path
        if: ${{ matrix.goos == 'windows' }}
        shell: bash
        run: echo "ASSET_PATH=echo-${{ matrix.goos }}-${{ matrix.goarch }}.exe" >> $GITHUB_ENV
      - name: Set Asset Path
        if: ${{ matrix.goos != 'windows' }}
        shell: bash
        run: echo "ASSET_PATH=echo-${{ matrix.goos }}-${{ matrix.goarch }}" >> $GITHUB_ENV
      - name: Build Client (${{ matrix.goos }}-${{ matrix.goarch }})
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -v -o ${{ env.ASSET_PATH }} ./cmd/echo/main.go
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ASSET_PATH }}
          path: ${{ env.ASSET_PATH }}
          if-no-files-found: error

  build_dpkg:
    name: Build DPKG Packages
    runs-on: ubuntu-latest
    needs:
      - build_artifacts
    strategy:
      matrix:
        goos:
          - linux
        goarch:
          - amd64
          - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Retrieve backend binaries
        uses: actions/download-artifact@v4
        with:
          name: echo-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/dpkg/usr/local/bin
      - name: Rename binary
        run: |
          mv dist/dpkg/usr/local/bin/echo* dist/dpkg/usr/local/bin/echo-server
          chmod +x dist/dpkg/usr/local/bin/echo-server
      - name: Build dpkg package
        run: |
          bash ./scripts/build-dpkg-package.sh ${{ matrix.goarch }} echo-${{ matrix.goos }}-${{ matrix.goarch }}.deb
          ls -lsh .
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: echo-${{ matrix.goos }}-${{ matrix.goarch }}.deb
          path: echo-${{ matrix.goos }}-${{ matrix.goarch }}.deb
          if-no-files-found: error

  create_release:
    name: Create GitHub Release
    needs:
      - build_artifacts
      - build_dpkg
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List downloaded files (debug)
        run: ls -lshR ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
